### ISSUE TITLE
说明源码版本

### ISSUE THREAD

**Issue by shanjianq** [doocs/source-code-hunter#119]
请问能否在解读源码的时候先注明源码的对应版本？这样看的话也能对的上，不然不知道扒哪个版本的源码去看

**Comment by yanglbme** [comment]
目前像 Netty 源码分析部分，都标注了版本。后续我们会完善，谢谢建议~

**Comment by yanglbme** [comment]
@Oliverwqcwrw 新添加的 RocketMQ 部分，可以在每篇文章加一个版本说明哈

**Comment by airoger125800** [comment]
好的感恩♥

**Comment by Oliverwqcwrw** [comment]
> @Oliverwqcwrw 新添加的 RocketMQ 部分，可以在每篇文章加一个版本说明哈

嗯那，这个建议不错

**Comment by Litexplorer** [comment]
你好，我已收到你的邮件。
