### ISSUE TITLE
ArrayList源码中关于get(index)的方法配图源码错误 

### ISSUE THREAD

**Issue by xuehairui** [doocs/source-code-hunter#152]
<img width="765" alt="image" src="https://github.com/doocs/source-code-hunter/assets/18653960/e3c20db3-1aa6-4c93-9dba-01e8ba323343">
如图所示的配图代码是subList中的方法, 可以修正如下图
<img width="308" alt="image" src="https://github.com/doocs/source-code-hunter/assets/18653960/e454f7bf-53c9-4451-a28b-e284ee2caf8e">

**Comment by yanglbme** [comment]
感谢反馈，已修正
