### ISSUE TITLE
乱码了！！！

### ISSUE THREAD

**Issue by endlonelycat** [doocs/source-code-hunter#55]
https://schunter.netlify.app/#/docs/Spring/clazz/Spring-StopWatch，这个网页里面的文字乱码了，不知道是不是我浏览器问题

**Comment by yanglbme** [comment]
@endlonelycat 谢谢反馈，这是文件编码问题。

![image](https://user-images.githubusercontent.com/21008209/82540797-10e94c00-9b82-11ea-8464-cd761b04ba45.png)

---

@AmyliaY @huifer 请统一项目所有文件编码为 `UTF-8`。

**Comment by AmyliaY** [comment]
@yanglbme 了解
