### ISSUE TITLE
文件命名规则

### ISSUE THREAD

**Issue by huifer** [doocs/source-code-hunter#6]
@AmyliaY  写一下文件命名规则

**Comment by yanglbme** [comment]
@huifer @AmyliaY 关于文件(夹)的命名（包括 .md/.jpg 等），我的建议是不使用中文，统一使用英文，如 xxx-yyy-zzz.md。

> 若使用中文，在分享 URL 时是很不友好的。比如：`https://github.com/doocs/source-code-hunter/tree/master/docs/学习心得` 会被显示成：https://github.com/doocs/source-code-hunter/tree/master/docs/%E5%AD%A6%E4%B9%A0%E5%BF%83%E5%BE%97

至于要不要用自己的 ID 开头，看项目维护者。

以上只是我的一点小建议。

**Comment by AmyliaY** [comment]
@huifer  
1、项目结构：mybatis的源码分析目前分为 “基础支持层”和“核心处理层”，项目结构在项目根目录的README文件中做了体现。看了你的内容，有的是在原本的内容上增加了更为丰富的解析，如：Reflector，也有一些本项目未分析过的源码，如ParamNameResolver、MapperMethod等，建议您将其归入合适的目录，具体可以看一下README文档的mybatis部分。
2、文件命名规则：不建议在文件名上体现自己的标识，可以在内容中，尤其是新增的博文中，标明自己的id
3、最近会考虑将贡献内容的 开发者 列入主页 贡献者名单，以保证其劳动权益
@yanglbme 关于文件夹的命名，我会尽量使用英文

**Comment by huifer** [comment]
thx
