### ISSUE TITLE
SpringBoot 日志系统 内容有误

### ISSUE THREAD

**Issue by GungnirLaevatain** [doocs/source-code-hunter#77]
[SpringBoot 日志系统](https://github.com/doocs/source-code-hunter/blob/master/docs/SpringBoot/SpringBoot-LogSystem.md) 这边文章现在的内容是在讲netty的而不是日志系统。
根据commit history，应该是**79217b535f44f7c99c5d82e9e2354e006cbf8d44**这个commit提交的有问题，希望能尽快修复下

**Comment by yanglbme** [comment]
@GungnirLaevatain 谢谢反馈，已修复
