### ISSUE TITLE
Sentinel时间窗口的实现.md 拼写错误

### ISSUE THREAD

**Issue by anaer** [doocs/source-code-hunter#92]
![image](https://user-images.githubusercontent.com/4637100/126763317-e36ac599-bb74-4123-8baa-d008debae4be.png)
![image](https://user-images.githubusercontent.com/4637100/126763813-663955c8-2aaf-4ece-8e4c-08012dee3f52.png)

**Comment by yanglbme** [comment]
已改正，感谢老铁😄~
