### ISSUE TITLE
文档中图片展示异常

### ISSUE THREAD

**Issue by JcookieChen** [doocs/source-code-hunter#98]
![image](https://user-images.githubusercontent.com/22971315/131431815-c40d9aa8-0135-42bf-8ce9-0a31549c5990.png)

**Comment by yanglbme** [comment]
![image](https://user-images.githubusercontent.com/21008209/131432707-c7183d89-1a4c-4608-bc65-672be6c66a2c.png)

是正常的哈，可能是网络问题 @JcookieChen

**Comment by JcookieChen** [comment]
是我这边dns有问题导致的，谢谢
